module.exports = {
  oci: [
    { id: 'oc-us-ashburn', name: 'OCI US East (Ashburn)', lat: 39.04, lng: -77.49, provider: 'Oracle OCI' },
    { id: 'oc-us-phoenix', name: 'OCI US West (Phoenix)', lat: 33.45, lng: -112.07, provider: 'Oracle OCI' },
    { id: 'oc-us-sanjose', name: 'OCI US West (San Jose)', lat: 37.34, lng: -121.89, provider: 'Oracle OCI' },
    { id: 'oc-us-chicago', name: 'OCI US Midwest (Chicago)', lat: 41.88, lng: -87.63, provider: 'Oracle OCI' },
    { id: 'oc-eu-frankfurt', name: 'OCI EU Central (Frankfurt)', lat: 50.11, lng: 8.68, provider: 'Oracle OCI' },
    { id: 'oc-eu-amsterdam', name: 'OCI EU NW (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Oracle OCI' },
    { id: 'oc-eu-london', name: 'OCI UK South (London)', lat: 51.51, lng: -0.13, provider: 'Oracle OCI' },
    { id: 'oc-eu-zurich', name: 'OCI EU North (Zurich)', lat: 47.38, lng: 8.54, provider: 'Oracle OCI' },
    { id: 'oc-eu-madrid', name: 'OCI EU South (Madrid)', lat: 40.42, lng: -3.70, provider: 'Oracle OCI' },
    { id: 'oc-eu-paris', name: 'OCI EU West (Paris)', lat: 48.86, lng: 2.35, provider: 'Oracle OCI' },
    { id: 'oc-eu-cardiff', name: 'OCI UK West (Cardiff)', lat: 51.48, lng: -3.18, provider: 'Oracle OCI' },
    { id: 'oc-eu-stockholm', name: 'OCI EU North (Stockholm)', lat: 59.33, lng: 18.07, provider: 'Oracle OCI' },
    { id: 'oc-eu-milan', name: 'OCI EU South (Milan)', lat: 45.46, lng: 9.19, provider: 'Oracle OCI' },
    { id: 'oc-eu-warsaw', name: 'OCI EU Central (Warsaw)', lat: 52.23, lng: 21.01, provider: 'Oracle OCI' },
    { id: 'oc-eu-marseille', name: 'OCI EU West (Marseille)', lat: 43.30, lng: 5.37, provider: 'Oracle OCI' },
    { id: 'oc-ap-tokyo', name: 'OCI AP East (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Oracle OCI' },
    { id: 'oc-ap-osaka', name: 'OCI AP Central (Osaka)', lat: 34.69, lng: 135.50, provider: 'Oracle OCI' },
    { id: 'oc-ap-seoul', name: 'OCI AP SE (Seoul)', lat: 37.57, lng: 126.98, provider: 'Oracle OCI' },
    { id: 'oc-ap-sydney', name: 'OCI AP SE (Sydney)', lat: -33.87, lng: 151.21, provider: 'Oracle OCI' },
    { id: 'oc-ap-melbourne', name: 'OCI AP SE (Melbourne)', lat: -37.81, lng: 144.96, provider: 'Oracle OCI' },
    { id: 'oc-ap-mumbai', name: 'OCI AP West (Mumbai)', lat: 19.08, lng: 72.88, provider: 'Oracle OCI' },
    { id: 'oc-ap-hyderabad', name: 'OCI AP South (Hyderabad)', lat: 17.39, lng: 78.49, provider: 'Oracle OCI' },
    { id: 'oc-sa-saopaulo', name: 'OCI LAD East (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'Oracle OCI' },
    { id: 'oc-sa-santiago', name: 'OCI LAD Central (Santiago)', lat: -33.45, lng: -70.67, provider: 'Oracle OCI' },
    { id: 'oc-me-dubai', name: 'OCI ME East (Dubai)', lat: 25.20, lng: 55.27, provider: 'Oracle OCI' },
    { id: 'oc-me-jeddah', name: 'OCI ME West (Jeddah)', lat: 21.49, lng: 39.19, provider: 'Oracle OCI' },
    { id: 'oc-af-johannesburg', name: 'OCI AF South (Johannesburg)', lat: -26.20, lng: 28.05, provider: 'Oracle OCI' },
    { id: 'oc-ca-toronto', name: 'OCI CA SE (Toronto)', lat: 43.65, lng: -79.38, provider: 'Oracle OCI' },
    { id: 'oc-ca-montreal', name: 'OCI CA SE (Montreal)', lat: 45.50, lng: -73.57, provider: 'Oracle OCI' },
  ],
  aws: [
    { id: 'aws-va', name: 'AWS US East (N. Virginia)', lat: 38.91, lng: -77.04, provider: 'AWS' },
    { id: 'aws-oh', name: 'AWS US East (Ohio)', lat: 39.96, lng: -83.00, provider: 'AWS' },
    { id: 'aws-ca', name: 'AWS US West (N. California)', lat: 37.34, lng: -121.89, provider: 'AWS' },
    { id: 'aws-or', name: 'AWS US West (Oregon)', lat: 45.52, lng: -122.68, provider: 'AWS' },
    { id: 'aws-ie', name: 'AWS EU (Ireland)', lat: 53.35, lng: -6.26, provider: 'AWS' },
    { id: 'aws-uk', name: 'AWS EU (London)', lat: 51.51, lng: -0.13, provider: 'AWS' },
    { id: 'aws-fr', name: 'AWS EU (Paris)', lat: 48.86, lng: 2.35, provider: 'AWS' },
    { id: 'aws-de', name: 'AWS EU (Frankfurt)', lat: 50.11, lng: 8.68, provider: 'AWS' },
    { id: 'aws-jp', name: 'AWS AP (Tokyo)', lat: 35.68, lng: 139.65, provider: 'AWS' },
    { id: 'aws-sg', name: 'AWS AP (Singapore)', lat: 1.35, lng: 103.82, provider: 'AWS' },
    { id: 'aws-au', name: 'AWS AP (Sydney)', lat: -33.87, lng: 151.21, provider: 'AWS' },
    { id: 'aws-in', name: 'AWS AP (Mumbai)', lat: 19.08, lng: 72.88, provider: 'AWS' },
    { id: 'aws-br', name: 'AWS SA (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'AWS' },
    { id: 'aws-bh', name: 'AWS ME (Bahrain)', lat: 26.07, lng: 50.56, provider: 'AWS' },
    { id: 'aws-za', name: 'AWS AF (Cape Town)', lat: -33.92, lng: 18.42, provider: 'AWS' },
  ],
  azure: [
    { id: 'az-va', name: 'Azure US East (Virginia)', lat: 37.43, lng: -79.13, provider: 'Azure' },
    { id: 'az-ca', name: 'Azure US West (California)', lat: 36.78, lng: -119.42, provider: 'Azure' },
    { id: 'az-nl', name: 'Azure EU West (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Azure' },
    { id: 'az-ie', name: 'Azure EU North (Dublin)', lat: 53.35, lng: -6.26, provider: 'Azure' },
    { id: 'az-uk', name: 'Azure UK South (London)', lat: 51.51, lng: -0.13, provider: 'Azure' },
    { id: 'az-jp', name: 'Azure AP (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Azure' },
    { id: 'az-sg', name: 'Azure AP (Singapore)', lat: 1.35, lng: 103.82, provider: 'Azure' },
    { id: 'az-br', name: 'Azure Brazil (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'Azure' },
    { id: 'az-ca-central', name: 'Azure Canada (Toronto)', lat: 43.65, lng: -79.38, provider: 'Azure' },
    { id: 'az-au', name: 'Azure Australia (Melbourne)', lat: -37.81, lng: 144.96, provider: 'Azure' },
  ],
  cloudflare: [
    { id: 'cf-nyc', name: 'Cloudflare NYC', lat: 40.71, lng: -74.01, provider: 'Cloudflare' },
    { id: 'cf-lax', name: 'Cloudflare LAX', lat: 34.05, lng: -118.24, provider: 'Cloudflare' },
    { id: 'cf-chi', name: 'Cloudflare Chicago', lat: 41.88, lng: -87.63, provider: 'Cloudflare' },
    { id: 'cf-lon', name: 'Cloudflare London', lat: 51.51, lng: -0.13, provider: 'Cloudflare' },
    { id: 'cf-fra', name: 'Cloudflare Frankfurt', lat: 50.11, lng: 8.68, provider: 'Cloudflare' },
    { id: 'cf-tok', name: 'Cloudflare Tokyo', lat: 35.68, lng: 139.65, provider: 'Cloudflare' },
    { id: 'cf-syd', name: 'Cloudflare Sydney', lat: -33.87, lng: 151.21, provider: 'Cloudflare' },
    { id: 'cf-sin', name: 'Cloudflare Singapore', lat: 1.35, lng: 103.82, provider: 'Cloudflare' },
    { id: 'cf-spo', name: 'Cloudflare Sao Paulo', lat: -23.55, lng: -46.63, provider: 'Cloudflare' },
    { id: 'cf-jnb', name: 'Cloudflare Johannesburg', lat: -26.20, lng: 28.05, provider: 'Cloudflare' },
    { id: 'cf-dxb', name: 'Cloudflare Dubai', lat: 25.20, lng: 55.27, provider: 'Cloudflare' },
    { id: 'cf-mum', name: 'Cloudflare Mumbai', lat: 19.08, lng: 72.88, provider: 'Cloudflare' },
  ],
  payment: [
    { id: 'visa-us', name: 'VisaNet (US)', lat: 37.39, lng: -122.08, provider: 'Visa' },
    { id: 'visa-eu', name: 'VisaNet (EU)', lat: 52.37, lng: 4.90, provider: 'Visa' },
    { id: 'mc-us', name: 'Mastercard (US)', lat: 40.76, lng: -73.99, provider: 'Mastercard' },
    { id: 'mc-eu', name: 'Mastercard (EU)', lat: 50.11, lng: 8.68, provider: 'Mastercard' },
    { id: 'stripe-us', name: 'Stripe (US)', lat: 37.77, lng: -122.42, provider: 'Stripe' },
    { id: 'amex-us', name: 'American Express (US)', lat: 40.76, lng: -73.99, provider: 'Amex' },
  ],
  banking: [
    { id: 'fin-nyc', name: 'NYC Financial Hub', lat: 40.71, lng: -74.01, provider: 'Financial Hub' },
    { id: 'fin-lon', name: 'London Financial Hub', lat: 51.51, lng: -0.13, provider: 'Financial Hub' },
    { id: 'fin-tok', name: 'Tokyo Financial Hub', lat: 35.68, lng: 139.65, provider: 'Financial Hub' },
    { id: 'fin-hk', name: 'Hong Kong Financial Hub', lat: 22.32, lng: 114.17, provider: 'Financial Hub' },
    { id: 'fin-sin', name: 'Singapore Financial Hub', lat: 1.35, lng: 103.82, provider: 'Financial Hub' },
    { id: 'fin-fra', name: 'Frankfurt Financial Hub', lat: 50.11, lng: 8.68, provider: 'Financial Hub' },
    { id: 'fin-zur', name: 'Zurich Financial Hub', lat: 47.38, lng: 8.54, provider: 'Financial Hub' },
  ],
  isp: [
    { id: 'isp-comcast', name: 'Comcast Hub', lat: 39.95, lng: -75.17, provider: 'Comcast' },
    { id: 'isp-att', name: 'AT&T Hub', lat: 32.78, lng: -96.80, provider: 'AT&T' },
    { id: 'isp-verizon', name: 'Verizon Hub', lat: 40.71, lng: -74.01, provider: 'Verizon' },
    { id: 'isp-bt', name: 'BT Hub (UK)', lat: 51.51, lng: -0.13, provider: 'BT' },
    { id: 'isp-dtag', name: 'Deutsche Telekom Hub', lat: 50.11, lng: 8.68, provider: 'Deutsche Telekom' },
    { id: 'isp-ntt', name: 'NTT Hub (Japan)', lat: 35.68, lng: 139.65, provider: 'NTT' },
    { id: 'isp-telstra', name: 'Telstra Hub (AU)', lat: -33.87, lng: 151.21, provider: 'Telstra' },
    { id: 'isp-jio', name: 'Jio Hub (India)', lat: 19.08, lng: 72.88, provider: 'Jio' },
    { id: 'isp-vodafone', name: 'Vodafone EU Hub', lat: 51.51, lng: -0.13, provider: 'Vodafone' },
  ],
  hospitality: [
    { id: 'h-marriott', name: 'Marriott HQ', lat: 38.98, lng: -77.09, provider: 'Marriott' },
    { id: 'h-hilton', name: 'Hilton HQ', lat: 38.92, lng: -77.23, provider: 'Hilton' },
    { id: 'h-ihg', name: 'IHG HQ (London)', lat: 51.51, lng: -0.13, provider: 'IHG' },
    { id: 'h-accor', name: 'Accor HQ (Paris)', lat: 48.86, lng: 2.35, provider: 'Accor' },
    { id: 'h-wyndham', name: 'Wyndham HQ', lat: 40.86, lng: -74.42, provider: 'Wyndham' },
    { id: 'h-hyatt', name: 'Hyatt HQ (Chicago)', lat: 41.88, lng: -87.63, provider: 'Hyatt' },
    { id: 'h-fourseasons', name: 'Four Seasons (Toronto)', lat: 43.65, lng: -79.38, provider: 'Four Seasons' },
    { id: 'h-nh', name: 'NH Hotels (Madrid)', lat: 40.42, lng: -3.70, provider: 'NH Hotels' },
    { id: 'h-radisson', name: 'Radisson HQ', lat: 44.98, lng: -93.27, provider: 'Radisson' },
    { id: 'h-choice', name: 'Choice Hotels HQ', lat: 39.08, lng: -77.15, provider: 'Choice Hotels' },
  ],
  dns: [
    { id: 'dns-google', name: 'Google DNS', lat: 37.41, lng: -122.08, provider: 'Google DNS' },
    { id: 'dns-cf', name: 'Cloudflare DNS', lat: 37.39, lng: -122.08, provider: 'Cloudflare DNS' },
    { id: 'dns-quad9', name: 'Quad9 DNS', lat: 47.38, lng: 8.54, provider: 'Quad9' },
  ],
  cables: [
    { id: 'cable-transatlantic', name: 'Transatlantic Cable', lat: 50.50, lng: -5.00, provider: 'Submarine Cable' },
    { id: 'cable-us-landing', name: 'US Cable Landing', lat: 41.50, lng: -71.50, provider: 'Submarine Cable' },
    { id: 'cable-sgp', name: 'APAC Cable Hub (Singapore)', lat: 1.35, lng: 103.82, provider: 'Submarine Cable' },
    { id: 'cable-marseille', name: 'Marseille Cable Hub', lat: 43.30, lng: 5.37, provider: 'Submarine Cable' },
    { id: 'cable-miami', name: 'Miami Cable Hub', lat: 25.76, lng: -80.19, provider: 'Submarine Cable' },
    { id: 'cable-la', name: 'LA Cable Hub', lat: 33.94, lng: -118.41, provider: 'Submarine Cable' },
    { id: 'cable-tyo', name: 'Tokyo Cable Hub', lat: 35.68, lng: 139.65, provider: 'Submarine Cable' },
    { id: 'cable-syd', name: 'Sydney Cable Hub', lat: -33.87, lng: 151.21, provider: 'Submarine Cable' },
    { id: 'cable-ct', name: 'Cape Town Cable Hub', lat: -33.92, lng: 18.42, provider: 'Submarine Cable' },
    { id: 'cable-mum', name: 'Mumbai Cable Hub', lat: 19.08, lng: 72.88, provider: 'Submarine Cable' },
  ],
  gcp: [
    { id: 'gcp-us-va', name: 'GCP US East (S. Carolina)', lat: 33.84, lng: -81.10, provider: 'Google Cloud' },
    { id: 'gcp-us-oregon', name: 'GCP US West (Oregon)', lat: 45.59, lng: -121.18, provider: 'Google Cloud' },
    { id: 'gcp-us-iowa', name: 'GCP US Central (Iowa)', lat: 41.26, lng: -95.86, provider: 'Google Cloud' },
    { id: 'gcp-eu-nl', name: 'GCP EU West (Netherlands)', lat: 52.37, lng: 4.90, provider: 'Google Cloud' },
    { id: 'gcp-eu-belgium', name: 'GCP EU West (Belgium)', lat: 50.47, lng: 4.47, provider: 'Google Cloud' },
    { id: 'gcp-eu-london', name: 'GCP EU West (London)', lat: 51.51, lng: -0.13, provider: 'Google Cloud' },
    { id: 'gcp-eu-frankfurt', name: 'GCP EU Central (Frankfurt)', lat: 50.11, lng: 8.68, provider: 'Google Cloud' },
    { id: 'gcp-ap-tokyo', name: 'GCP AP (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Google Cloud' },
    { id: 'gcp-ap-singapore', name: 'GCP AP (Singapore)', lat: 1.35, lng: 103.82, provider: 'Google Cloud' },
    { id: 'gcp-ap-sydney', name: 'GCP AP (Sydney)', lat: -33.87, lng: 151.21, provider: 'Google Cloud' },
    { id: 'gcp-ap-mumbai', name: 'GCP AP (Mumbai)', lat: 19.08, lng: 72.88, provider: 'Google Cloud' },
    { id: 'gcp-sa-saopaulo', name: 'GCP LAD (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'Google Cloud' },
  ],
  cdn: [
    { id: 'cdn-akamai-va', name: 'Akamai (Virginia)', lat: 38.91, lng: -77.04, provider: 'Akamai' },
    { id: 'cdn-akamai-lon', name: 'Akamai (London)', lat: 51.51, lng: -0.13, provider: 'Akamai' },
    { id: 'cdn-akamai-sgp', name: 'Akamai (Singapore)', lat: 1.35, lng: 103.82, provider: 'Akamai' },
    { id: 'cdn-akamai-tok', name: 'Akamai (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Akamai' },
    { id: 'cdn-fastly-us', name: 'Fastly (US)', lat: 37.77, lng: -122.42, provider: 'Fastly' },
    { id: 'cdn-fastly-eu', name: 'Fastly (EU)', lat: 50.11, lng: 8.68, provider: 'Fastly' },
    { id: 'cdn-fastly-ap', name: 'Fastly (APAC)', lat: 1.35, lng: 103.82, provider: 'Fastly' },
    { id: 'cdn-imdg', name: 'Imperva/Incapsula (Global)', lat: 38.91, lng: -77.04, provider: 'Imperva' },
  ],
  itsm: [
    { id: 'itsm-snow-us', name: 'ServiceNow (US HQ)', lat: 37.39, lng: -122.08, provider: 'ServiceNow' },
    { id: 'itsm-snow-uk', name: 'ServiceNow (UK)', lat: 51.51, lng: -0.13, provider: 'ServiceNow' },
    { id: 'itsm-jira-au', name: 'Atlassian/Jira (Sydney)', lat: -33.87, lng: 151.21, provider: 'Atlassian' },
    { id: 'itsm-jira-us', name: 'Atlassian/Jira (US)', lat: 37.39, lng: -122.08, provider: 'Atlassian' },
    { id: 'itsm-fresh', name: 'Freshservice (Bangalore)', lat: 12.97, lng: 77.59, provider: 'Freshservice' },
    { id: 'itsm-bmc', name: 'BMC Remedy (US)', lat: 33.75, lng: -84.39, provider: 'BMC' },
    { id: 'itsm-ivanti', name: 'Ivanti (Salt Lake City)', lat: 40.76, lng: -111.89, provider: 'Ivanti' },
    { id: 'itsm-cherwell', name: 'Cherwell/BMC (Colorado)', lat: 38.83, lng: -104.82, provider: 'Cherwell' },
  ],
  rmm: [
    { id: 'rmm-datto', name: 'Datto HQ (Stamford)', lat: 41.05, lng: -73.54, provider: 'Datto' },
    { id: 'rmm-datto-uk', name: 'Datto (UK)', lat: 51.51, lng: -0.13, provider: 'Datto' },
    { id: 'rmm-kaseya', name: 'Kaseya HQ (Miami)', lat: 25.76, lng: -80.19, provider: 'Kaseya' },
    { id: 'rmm-kaseya-dub', name: 'Kaseya (Dublin)', lat: 53.35, lng: -6.26, provider: 'Kaseya' },
    { id: 'rmm-cw', name: 'ConnectWise (Tampa)', lat: 27.95, lng: -82.46, provider: 'ConnectWise' },
    { id: 'rmm-ninja', name: 'NinjaRMM/RMM+ (Boston)', lat: 42.36, lng: -71.06, provider: 'NinjaRMM' },
    { id: 'rmm-pulseway', name: 'Pulseway (Dublin)', lat: 53.35, lng: -6.26, provider: 'Pulseway' },
    { id: 'rmm-aem', name: 'Atera (Tel Aviv)', lat: 32.09, lng: 34.78, provider: 'Atera' },
    { id: 'rmm-superops', name: 'SuperOps (Dallas)', lat: 32.78, lng: -96.80, provider: 'SuperOps' },
  ],
  virtualisation: [
    { id: 'virt-vmw', name: 'VMware/Broadcom (Palo Alto)', lat: 37.44, lng: -122.16, provider: 'VMware' },
    { id: 'virt-vmw-uk', name: 'VMware (UK)', lat: 51.51, lng: -0.13, provider: 'VMware' },
    { id: 'virt-citrix', name: 'Cloud Software Group/FW (Fort Lauderdale)', lat: 26.12, lng: -80.14, provider: 'Citrix' },
    { id: 'virt-citrix-uk', name: 'Citrix (UK)', lat: 51.51, lng: -0.13, provider: 'Citrix' },
    { id: 'virt-ms-rd', name: 'Microsoft RDS/Azure Virtual Desktop', lat: 47.61, lng: -122.33, provider: 'Microsoft RDS' },
    { id: 'virt-horizon', name: 'VMware Horizon Cloud', lat: 37.44, lng: -122.16, provider: 'VMware Horizon' },
  ],
  backup: [
    { id: 'bkp-veeam', name: 'Veeam HQ (Columbus)', lat: 39.96, lng: -83.00, provider: 'Veeam' },
    { id: 'bkp-veeam-de', name: 'Veeam (Germany)', lat: 50.11, lng: 8.68, provider: 'Veeam' },
    { id: 'bkp-acronis', name: 'Acronis (Singapore)', lat: 1.35, lng: 103.82, provider: 'Acronis' },
    { id: 'bkp-acronis-us', name: 'Acronis (US)', lat: 42.36, lng: -71.06, provider: 'Acronis' },
    { id: 'bkp-datto-bk', name: 'Datto BCDR (Stamford)', lat: 41.05, lng: -73.54, provider: 'Datto BCDR' },
    { id: 'bkp-unitrends', name: 'Unitrends/Barracuda (Burlington)', lat: 42.50, lng: -71.20, provider: 'Unitrends' },
    { id: 'bkp-storagecraft', name: 'StorageCraft/arcserve (Draper)', lat: 40.53, lng: -111.87, provider: 'StorageCraft' },
    { id: 'bkp-zerto', name: 'Zerto/ITG (Boston)', lat: 42.36, lng: -71.06, provider: 'Zerto' },
  ],
  pos: [
    { id: 'pos-toast', name: 'Toast POS HQ (Boston)', lat: 42.36, lng: -71.06, provider: 'Toast' },
    { id: 'pos-toast-us', name: 'Toast (US Cloud)', lat: 39.76, lng: -86.16, provider: 'Toast' },
    { id: 'pos-square', name: 'Block/Square (SF)', lat: 37.77, lng: -122.42, provider: 'Square' },
    { id: 'pos-clover', name: 'Clover/Fiserv (Atlanta)', lat: 33.75, lng: -84.39, provider: 'Clover' },
    { id: 'pos-micros', name: 'Oracle MICROS (Columbia)', lat: 39.20, lng: -76.84, provider: 'Oracle MICROS' },
    { id: 'pos-micros-uk', name: 'Oracle MICROS (UK)', lat: 51.51, lng: -0.13, provider: 'Oracle MICROS' },
    { id: 'pos-adyen', name: 'Adyen HQ (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Adyen' },
    { id: 'pos-worldpay', name: 'Worldpay/FIS (Cincinnati)', lat: 39.10, lng: -84.51, provider: 'Worldpay' },
    { id: 'pos-nuvei', name: 'Nuvei (Montreal)', lat: 45.50, lng: -73.57, provider: 'Nuvei' },
    { id: 'pos-revel', name: 'Revel Systems (SF)', lat: 37.77, lng: -122.42, provider: 'Revel Systems' },
    { id: 'pos-lightspeed', name: 'Lightspeed (Montreal)', lat: 45.50, lng: -73.57, provider: 'Lightspeed' },
    { id: 'pos-elo', name: 'Elo Pay (Austin)', lat: 30.27, lng: -97.74, provider: 'Elo Pay' },
  ],
  pms: [
    { id: 'pms-opera', name: 'Oracle Opera PMS (Global)', lat: 37.39, lng: -122.08, provider: 'Oracle Opera PMS' },
    { id: 'pms-opera-emea', name: 'Oracle Opera PMS (EMEA)', lat: 51.51, lng: -0.13, provider: 'Oracle Opera PMS' },
    { id: 'pms-opera-apac', name: 'Oracle Opera PMS (APAC)', lat: 1.35, lng: 103.82, provider: 'Oracle Opera PMS' },
    { id: 'pms-agilysys', name: 'Agilysys HQ (Alpharetta)', lat: 34.07, lng: -84.29, provider: 'Agilysys' },
    { id: 'pms-mews', name: 'Mews (Prague)', lat: 50.08, lng: 14.44, provider: 'Mews' },
    { id: 'pms-cloudbeds', name: 'Cloudbeds (San Diego)', lat: 32.72, lng: -117.16, provider: 'Cloudbeds' },
    { id: 'pms-roomkey', name: 'RoomKeyPMS (Vancouver)', lat: 49.28, lng: -123.12, provider: 'RoomKeyPMS' },
    { id: 'pms-hotelogix', name: 'Hotelogix (Noida)', lat: 28.57, lng: 77.34, provider: 'Hotelogix' },
    { id: 'pms-protel', name: 'Protel/Mews (Berlin)', lat: 52.52, lng: 13.41, provider: 'Protel' },
    { id: 'pms-clock', name: 'Clock PMS+ (Sofia)', lat: 42.70, lng: 23.32, provider: 'Clock PMS+' },
    { id: 'pms-site-minder', name: 'SiteMinder (Sydney)', lat: -33.87, lng: 151.21, provider: 'SiteMinder' },
  ],
  idp: [
    { id: 'idp-okta', name: 'Okta (SF)', lat: 37.77, lng: -122.42, provider: 'Okta' },
    { id: 'idp-okta-uk', name: 'Okta (UK)', lat: 51.51, lng: -0.13, provider: 'Okta' },
    { id: 'idp-azure-ad', name: 'Azure AD/Entra ID (Global)', lat: 47.61, lng: -122.33, provider: 'Azure AD' },
    { id: 'idp-ping', name: 'Ping Identity (Denver)', lat: 39.74, lng: -104.99, provider: 'Ping Identity' },
    { id: 'idp-auth0', name: 'Auth0/Okta (Bellevue)', lat: 47.61, lng: -122.20, provider: 'Auth0' },
    { id: 'idp-forgerock', name: 'Forgerock (SF)', lat: 37.77, lng: -122.42, provider: 'Forgerock' },
  ],
  collaboration: [
    { id: 'col-zoom', name: 'Zoom (San Jose)', lat: 37.34, lng: -121.89, provider: 'Zoom' },
    { id: 'col-slack', name: 'Slack/Salesforce (SF)', lat: 37.77, lng: -122.42, provider: 'Slack' },
    { id: 'col-teams', name: 'Microsoft Teams (Redmond)', lat: 47.68, lng: -122.12, provider: 'Microsoft Teams' },
    { id: 'col-webex', name: 'Cisco Webex (San Jose)', lat: 37.34, lng: -121.89, provider: 'Cisco Webex' },
    { id: 'col-gmeet', name: 'Google Meet (Mountain View)', lat: 37.39, lng: -122.08, provider: 'Google Meet' },
  ],
  monitoring: [
    { id: 'mon-datadog', name: 'Datadog (NYC)', lat: 40.71, lng: -74.01, provider: 'Datadog' },
    { id: 'mon-prtg', name: 'PRTG/N Paessler (Nuremberg)', lat: 49.45, lng: 11.08, provider: 'PRTG' },
    { id: 'mon-solarwinds', name: 'SolarWinds (Austin)', lat: 30.27, lng: -97.74, provider: 'SolarWinds' },
    { id: 'mon-nagios', name: 'Nagios (St. Paul)', lat: 44.94, lng: -93.10, provider: 'Nagios' },
    { id: 'mon-zabbix', name: 'Zabbix (Riga)', lat: 56.95, lng: 24.11, provider: 'Zabbix' },
    { id: 'mon-logicmonitor', name: 'LogicMonitor (Santa Barbara)', lat: 34.42, lng: -119.70, provider: 'LogicMonitor' },
    { id: 'mon-uptime', name: 'UptimeRobot/Robot (San Francisco)', lat: 37.77, lng: -122.42, provider: 'UptimeRobot' },
  ],
  hosting: [
    { id: 'host-godaddy', name: 'GoDaddy (Tempe)', lat: 33.42, lng: -111.94, provider: 'GoDaddy' },
    { id: 'host-do', name: 'DigitalOcean (NYC)', lat: 40.71, lng: -74.01, provider: 'DigitalOcean' },
    { id: 'host-vultr', name: 'Vultr (Westfield)', lat: 40.66, lng: -74.34, provider: 'Vultr' },
    { id: 'host-hetzner', name: 'Hetzner (Nuremberg)', lat: 49.45, lng: 11.08, provider: 'Hetzner' },
    { id: 'host-linode', name: 'Akamai/Linode (Philadelphia)', lat: 39.95, lng: -75.17, provider: 'Linode' },
    { id: 'host-rackspace', name: 'Rackspace (San Antonio)', lat: 29.42, lng: -98.49, provider: 'Rackspace' },
    { id: 'host-ovh', name: 'OVH (Roubaix)', lat: 50.69, lng: 3.18, provider: 'OVH' },
  ],
  email: [
    { id: 'email-sendgrid', name: 'SendGrid/Twilio (Boulder)', lat: 40.01, lng: -105.27, provider: 'SendGrid' },
    { id: 'email-mailgun', name: 'Mailgun (SF)', lat: 37.77, lng: -122.42, provider: 'Mailgun' },
    { id: 'email-mandrill', name: 'Mandrill/Mailchimp (Atlanta)', lat: 33.75, lng: -84.39, provider: 'Mailchimp' },
    { id: 'email-postmark', name: 'Postmark/Wildbit (Philly)', lat: 39.95, lng: -75.17, provider: 'Postmark' },
  ],
  db: [
    { id: 'db-mysql', name: 'MySQL/Oracle (Redwood Shores)', lat: 37.52, lng: -122.27, provider: 'MySQL' },
    { id: 'db-pg', name: 'PostgreSQL/EDB (Bedford)', lat: 42.49, lng: -71.28, provider: 'PostgreSQL' },
    { id: 'db-redis', name: 'Redis Labs (Mountain View)', lat: 37.39, lng: -122.08, provider: 'Redis' },
    { id: 'db-mongo', name: 'MongoDB (NYC)', lat: 40.71, lng: -74.01, provider: 'MongoDB' },
    { id: 'db-elastic', name: 'Elastic (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Elastic' },
    { id: 'db-cosmos', name: 'Azure Cosmos DB (Global)', lat: 47.61, lng: -122.33, provider: 'Cosmos DB' },
  ],
};
