module.exports = {
  oci: [
    { id: 'oc-us-ashburn', name: 'OCI US East (Ashburn)', lat: 39.04, lng: -77.49, provider: 'Oracle OCI' },
    { id: 'oc-us-phoenix', name: 'OCI US West (Phoenix)', lat: 33.45, lng: -112.07, provider: 'Oracle OCI' },
    { id: 'oc-us-sanjose', name: 'OCI US West (San Jose)', lat: 37.34, lng: -121.89, provider: 'Oracle OCI' },
    { id: 'oc-us-chicago', name: 'OCI US Midwest (Chicago)', lat: 41.88, lng: -87.63, provider: 'Oracle OCI' },
    { id: 'oc-eu-frankfurt', name: 'OCI EU Central (Frankfurt)', lat: 50.11, lng: 8.68, provider: 'Oracle OCI' },
    { id: 'oc-eu-amsterdam', name: 'OCI EU NW (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Oracle OCI' },
    { id: 'oc-eu-london', name: 'OCI UK South (London)', lat: 51.51, lng: -0.13, provider: 'Oracle OCI' },
    { id: 'oc-eu-zurich', name: 'OCI EU North (Zurich)', lat: 47.38, lng: 8.54, provider: 'Oracle OCI' },
    { id: 'oc-eu-madrid', name: 'OCI EU South (Madrid)', lat: 40.42, lng: -3.70, provider: 'Oracle OCI' },
    { id: 'oc-eu-paris', name: 'OCI EU West (Paris)', lat: 48.86, lng: 2.35, provider: 'Oracle OCI' },
    { id: 'oc-eu-cardiff', name: 'OCI UK West (Cardiff)', lat: 51.48, lng: -3.18, provider: 'Oracle OCI' },
    { id: 'oc-eu-stockholm', name: 'OCI EU North (Stockholm)', lat: 59.33, lng: 18.07, provider: 'Oracle OCI' },
    { id: 'oc-eu-milan', name: 'OCI EU South (Milan)', lat: 45.46, lng: 9.19, provider: 'Oracle OCI' },
    { id: 'oc-eu-warsaw', name: 'OCI EU Central (Warsaw)', lat: 52.23, lng: 21.01, provider: 'Oracle OCI' },
    { id: 'oc-eu-marseille', name: 'OCI EU West (Marseille)', lat: 43.30, lng: 5.37, provider: 'Oracle OCI' },
    { id: 'oc-ap-tokyo', name: 'OCI AP East (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Oracle OCI' },
    { id: 'oc-ap-osaka', name: 'OCI AP Central (Osaka)', lat: 34.69, lng: 135.50, provider: 'Oracle OCI' },
    { id: 'oc-ap-seoul', name: 'OCI AP SE (Seoul)', lat: 37.57, lng: 126.98, provider: 'Oracle OCI' },
    { id: 'oc-ap-sydney', name: 'OCI AP SE (Sydney)', lat: -33.87, lng: 151.21, provider: 'Oracle OCI' },
    { id: 'oc-ap-melbourne', name: 'OCI AP SE (Melbourne)', lat: -37.81, lng: 144.96, provider: 'Oracle OCI' },
    { id: 'oc-ap-mumbai', name: 'OCI AP West (Mumbai)', lat: 19.08, lng: 72.88, provider: 'Oracle OCI' },
    { id: 'oc-ap-hyderabad', name: 'OCI AP South (Hyderabad)', lat: 17.39, lng: 78.49, provider: 'Oracle OCI' },
    { id: 'oc-sa-saopaulo', name: 'OCI LAD East (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'Oracle OCI' },
    { id: 'oc-sa-santiago', name: 'OCI LAD Central (Santiago)', lat: -33.45, lng: -70.67, provider: 'Oracle OCI' },
    { id: 'oc-me-dubai', name: 'OCI ME East (Dubai)', lat: 25.20, lng: 55.27, provider: 'Oracle OCI' },
    { id: 'oc-me-jeddah', name: 'OCI ME West (Jeddah)', lat: 21.49, lng: 39.19, provider: 'Oracle OCI' },
    { id: 'oc-af-johannesburg', name: 'OCI AF South (Johannesburg)', lat: -26.20, lng: 28.05, provider: 'Oracle OCI' },
    { id: 'oc-ca-toronto', name: 'OCI CA SE (Toronto)', lat: 43.65, lng: -79.38, provider: 'Oracle OCI' },
    { id: 'oc-ca-montreal', name: 'OCI CA SE (Montreal)', lat: 45.50, lng: -73.57, provider: 'Oracle OCI' },
  ],
  aws: [
    { id: 'aws-va', name: 'AWS US East (N. Virginia)', lat: 38.91, lng: -77.04, provider: 'AWS' },
    { id: 'aws-oh', name: 'AWS US East (Ohio)', lat: 39.96, lng: -83.00, provider: 'AWS' },
    { id: 'aws-ca', name: 'AWS US West (N. California)', lat: 37.34, lng: -121.89, provider: 'AWS' },
    { id: 'aws-or', name: 'AWS US West (Oregon)', lat: 45.52, lng: -122.68, provider: 'AWS' },
    { id: 'aws-ie', name: 'AWS EU (Ireland)', lat: 53.35, lng: -6.26, provider: 'AWS' },
    { id: 'aws-uk', name: 'AWS EU (London)', lat: 51.51, lng: -0.13, provider: 'AWS' },
    { id: 'aws-fr', name: 'AWS EU (Paris)', lat: 48.86, lng: 2.35, provider: 'AWS' },
    { id: 'aws-de', name: 'AWS EU (Frankfurt)', lat: 50.11, lng: 8.68, provider: 'AWS' },
    { id: 'aws-jp', name: 'AWS AP (Tokyo)', lat: 35.68, lng: 139.65, provider: 'AWS' },
    { id: 'aws-sg', name: 'AWS AP (Singapore)', lat: 1.35, lng: 103.82, provider: 'AWS' },
    { id: 'aws-au', name: 'AWS AP (Sydney)', lat: -33.87, lng: 151.21, provider: 'AWS' },
    { id: 'aws-in', name: 'AWS AP (Mumbai)', lat: 19.08, lng: 72.88, provider: 'AWS' },
    { id: 'aws-br', name: 'AWS SA (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'AWS' },
    { id: 'aws-bh', name: 'AWS ME (Bahrain)', lat: 26.07, lng: 50.56, provider: 'AWS' },
    { id: 'aws-za', name: 'AWS AF (Cape Town)', lat: -33.92, lng: 18.42, provider: 'AWS' },
  ],
  azure: [
    { id: 'az-va', name: 'Azure US East (Virginia)', lat: 37.43, lng: -79.13, provider: 'Azure' },
    { id: 'az-ca', name: 'Azure US West (California)', lat: 36.78, lng: -119.42, provider: 'Azure' },
    { id: 'az-nl', name: 'Azure EU West (Amsterdam)', lat: 52.37, lng: 4.90, provider: 'Azure' },
    { id: 'az-ie', name: 'Azure EU North (Dublin)', lat: 53.35, lng: -6.26, provider: 'Azure' },
    { id: 'az-uk', name: 'Azure UK South (London)', lat: 51.51, lng: -0.13, provider: 'Azure' },
    { id: 'az-jp', name: 'Azure AP (Tokyo)', lat: 35.68, lng: 139.65, provider: 'Azure' },
    { id: 'az-sg', name: 'Azure AP (Singapore)', lat: 1.35, lng: 103.82, provider: 'Azure' },
    { id: 'az-br', name: 'Azure Brazil (Sao Paulo)', lat: -23.55, lng: -46.63, provider: 'Azure' },
    { id: 'az-ca-central', name: 'Azure Canada (Toronto)', lat: 43.65, lng: -79.38, provider: 'Azure' },
    { id: 'az-au', name: 'Azure Australia (Melbourne)', lat: -37.81, lng: 144.96, provider: 'Azure' },
  ],
  cloudflare: [
    { id: 'cf-nyc', name: 'Cloudflare NYC', lat: 40.71, lng: -74.01, provider: 'Cloudflare' },
    { id: 'cf-lax', name: 'Cloudflare LAX', lat: 34.05, lng: -118.24, provider: 'Cloudflare' },
    { id: 'cf-chi', name: 'Cloudflare Chicago', lat: 41.88, lng: -87.63, provider: 'Cloudflare' },
    { id: 'cf-lon', name: 'Cloudflare London', lat: 51.51, lng: -0.13, provider: 'Cloudflare' },
    { id: 'cf-fra', name: 'Cloudflare Frankfurt', lat: 50.11, lng: 8.68, provider: 'Cloudflare' },
    { id: 'cf-tok', name: 'Cloudflare Tokyo', lat: 35.68, lng: 139.65, provider: 'Cloudflare' },
    { id: 'cf-syd', name: 'Cloudflare Sydney', lat: -33.87, lng: 151.21, provider: 'Cloudflare' },
    { id: 'cf-sin', name: 'Cloudflare Singapore', lat: 1.35, lng: 103.82, provider: 'Cloudflare' },
    { id: 'cf-spo', name: 'Cloudflare Sao Paulo', lat: -23.55, lng: -46.63, provider: 'Cloudflare' },
    { id: 'cf-jnb', name: 'Cloudflare Johannesburg', lat: -26.20, lng: 28.05, provider: 'Cloudflare' },
    { id: 'cf-dxb', name: 'Cloudflare Dubai', lat: 25.20, lng: 55.27, provider: 'Cloudflare' },
    { id: 'cf-mum', name: 'Cloudflare Mumbai', lat: 19.08, lng: 72.88, provider: 'Cloudflare' },
  ],
  payment: [
    { id: 'visa-us', name: 'VisaNet (US)', lat: 37.39, lng: -122.08, provider: 'Visa' },
    { id: 'visa-eu', name: 'VisaNet (EU)', lat: 52.37, lng: 4.90, provider: 'Visa' },
    { id: 'mc-us', name: 'Mastercard (US)', lat: 40.76, lng: -73.99, provider: 'Mastercard' },
    { id: 'mc-eu', name: 'Mastercard (EU)', lat: 50.11, lng: 8.68, provider: 'Mastercard' },
    { id: 'stripe-us', name: 'Stripe (US)', lat: 37.77, lng: -122.42, provider: 'Stripe' },
    { id: 'amex-us', name: 'American Express (US)', lat: 40.76, lng: -73.99, provider: 'Amex' },
  ],
  banking: [
    { id: 'fin-nyc', name: 'NYC Financial Hub', lat: 40.71, lng: -74.01, provider: 'Financial Hub' },
    { id: 'fin-lon', name: 'London Financial Hub', lat: 51.51, lng: -0.13, provider: 'Financial Hub' },
    { id: 'fin-tok', name: 'Tokyo Financial Hub', lat: 35.68, lng: 139.65, provider: 'Financial Hub' },
    { id: 'fin-hk', name: 'Hong Kong Financial Hub', lat: 22.32, lng: 114.17, provider: 'Financial Hub' },
    { id: 'fin-sin', name: 'Singapore Financial Hub', lat: 1.35, lng: 103.82, provider: 'Financial Hub' },
    { id: 'fin-fra', name: 'Frankfurt Financial Hub', lat: 50.11, lng: 8.68, provider: 'Financial Hub' },
    { id: 'fin-zur', name: 'Zurich Financial Hub', lat: 47.38, lng: 8.54, provider: 'Financial Hub' },
  ],
  isp: [
    { id: 'isp-comcast', name: 'Comcast Hub', lat: 39.95, lng: -75.17, provider: 'Comcast' },
    { id: 'isp-att', name: 'AT&T Hub', lat: 32.78, lng: -96.80, provider: 'AT&T' },
    { id: 'isp-verizon', name: 'Verizon Hub', lat: 40.71, lng: -74.01, provider: 'Verizon' },
    { id: 'isp-bt', name: 'BT Hub (UK)', lat: 51.51, lng: -0.13, provider: 'BT' },
    { id: 'isp-dtag', name: 'Deutsche Telekom Hub', lat: 50.11, lng: 8.68, provider: 'Deutsche Telekom' },
    { id: 'isp-ntt', name: 'NTT Hub (Japan)', lat: 35.68, lng: 139.65, provider: 'NTT' },
    { id: 'isp-telstra', name: 'Telstra Hub (AU)', lat: -33.87, lng: 151.21, provider: 'Telstra' },
    { id: 'isp-jio', name: 'Jio Hub (India)', lat: 19.08, lng: 72.88, provider: 'Jio' },
    { id: 'isp-vodafone', name: 'Vodafone EU Hub', lat: 51.51, lng: -0.13, provider: 'Vodafone' },
  ],
  hospitality: [
    { id: 'h-marriott', name: 'Marriott HQ', lat: 38.98, lng: -77.09, provider: 'Marriott' },
    { id: 'h-hilton', name: 'Hilton HQ', lat: 38.92, lng: -77.23, provider: 'Hilton' },
    { id: 'h-ihg', name: 'IHG HQ (London)', lat: 51.51, lng: -0.13, provider: 'IHG' },
    { id: 'h-accor', name: 'Accor HQ (Paris)', lat: 48.86, lng: 2.35, provider: 'Accor' },
    { id: 'h-wyndham', name: 'Wyndham HQ', lat: 40.86, lng: -74.42, provider: 'Wyndham' },
    { id: 'h-hyatt', name: 'Hyatt HQ (Chicago)', lat: 41.88, lng: -87.63, provider: 'Hyatt' },
    { id: 'h-fourseasons', name: 'Four Seasons (Toronto)', lat: 43.65, lng: -79.38, provider: 'Four Seasons' },
    { id: 'h-nh', name: 'NH Hotels (Madrid)', lat: 40.42, lng: -3.70, provider: 'NH Hotels' },
    { id: 'h-radisson', name: 'Radisson HQ', lat: 44.98, lng: -93.27, provider: 'Radisson' },
    { id: 'h-choice', name: 'Choice Hotels HQ', lat: 39.08, lng: -77.15, provider: 'Choice Hotels' },
  ],
  dns: [
    { id: 'dns-google', name: 'Google DNS', lat: 37.41, lng: -122.08, provider: 'Google DNS' },
    { id: 'dns-cf', name: 'Cloudflare DNS', lat: 37.39, lng: -122.08, provider: 'Cloudflare DNS' },
    { id: 'dns-quad9', name: 'Quad9 DNS', lat: 47.38, lng: 8.54, provider: 'Quad9' },
  ],
  cables: [
    { id: 'cable-transatlantic', name: 'Transatlantic Cable', lat: 50.50, lng: -5.00, provider: 'Submarine Cable' },
    { id: 'cable-us-landing', name: 'US Cable Landing', lat: 41.50, lng: -71.50, provider: 'Submarine Cable' },
    { id: 'cable-sgp', name: 'APAC Cable Hub (Singapore)', lat: 1.35, lng: 103.82, provider: 'Submarine Cable' },
    { id: 'cable-marseille', name: 'Marseille Cable Hub', lat: 43.30, lng: 5.37, provider: 'Submarine Cable' },
    { id: 'cable-miami', name: 'Miami Cable Hub', lat: 25.76, lng: -80.19, provider: 'Submarine Cable' },
    { id: 'cable-la', name: 'LA Cable Hub', lat: 33.94, lng: -118.41, provider: 'Submarine Cable' },
    { id: 'cable-tyo', name: 'Tokyo Cable Hub', lat: 35.68, lng: 139.65, provider: 'Submarine Cable' },
    { id: 'cable-syd', name: 'Sydney Cable Hub', lat: -33.87, lng: 151.21, provider: 'Submarine Cable' },
    { id: 'cable-ct', name: 'Cape Town Cable Hub', lat: -33.92, lng: 18.42, provider: 'Submarine Cable' },
    { id: 'cable-mum', name: 'Mumbai Cable Hub', lat: 19.08, lng: 72.88, provider: 'Submarine Cable' },
  ]
};
